[project]
name = "copilot_tests"
version = "0.1.0"
description = "A Python project managed with uv and pyproject.toml."
requires-python = ">=3.8"
dependencies = [
    "jax",
    "jaxlib"
]

[tool.uv]
# Add uv-specific configuration here if needed
